## Exercises about last week

Lists:
- Write a Python function that takes a list of integers as an input and returns the sum of all the even numbers in the list.
- <b>Write a Python program that takes two lists and returns a new list that contains only the common elements between the two lists.</b>
- Write a Python program that removes duplicates from a given list and returns the new list.

Dictionaries:
- Write a Python program that creates a dictionary of words and their frequencies in a given string.
- Write a Python program that takes a dictionary and returns a new dictionary with keys and values swapped.
- Write a Python program that merges two dictionaries.

Tuples (like lists but can't be modified):
- Write a Python program that takes a list of tuples and sorts them by the second element of each tuple.
- Write a Python program that creates a tuple of the first 10 Fibonacci numbers.
- <b>Write a Python program that takes a tuple of integers and returns the sum of all the even numbers in the tuple.</b>

Sets (no duplicates in here ever):
- Write a Python program that takes two sets and returns a new set that contains only the elements that are in both sets.
- Write a Python program that removes all the duplicates from a given set.
- Write a Python program that checks if a given set is a subset of another set.

Loops:
- Write a Python program that prints all the prime numbers between 1 and 100.
- <b>Write a Python program that takes a list of integers and prints the square of each number. --> return list</b>
- Write a Python program that prints the multiplication table of a given number.

If structures:
- Write a Python program that takes an integer and prints whether it is even or odd.
- Write a Python program that takes three integers and prints the maximum of the three.
- Write a Python program that takes a string and checks whether it is a palindrome or not.

In [17]:
def Commons(List1, List2):
    commonList = []
    for L1 in List1:
        if L1 in List2:
            commonList.append(int(L1))
    return commonList

List1 = input().split()
#List1 = [int(i) for i in List1]
List2 = input().split()
#List2 = [int(i) for i in List2]

print(Commons(List1,List2))


[1, 3]


In [21]:
def Sum(Tup):
    Tup = Tup.split()
    Tup = tuple(Tup)
    totalSum = sum(int(T) for T in Tup if int(T) % 2 == 0)
    return totalSum

Tup = input()
print(Sum(Tup))

('1', '2', '3', '4', '5', '6')
12


In [26]:
def Squared(L):
    L = [i**2 for i in L]
    return L

L = [int(i) for i in input().split()]
print(Squared(L))


[1, 4, 9]


In [1]:
def commons(list1, list2):
    commonElements = list(set(list1) & set(list2))
    return commonElements

input1 = input().split() #checks spaces
input2 = input().split() #checks spaces

list1 = [int(i) for i in input1]
list2 = [int(i) for i in input2]

C = commons(list1, list2)
print("Common elements:", C)

Common elements: [2, 3]


In [7]:
def Sum(T):
    total = 0
    for number in T:
        if number % 2 == 0:
            total += number
    return total

stringcheck = input().split()
T = tuple(int(number) for number in stringcheck)
sumcheck = Sum(T)
print(T)
print(sumcheck)

(1, 2, 3, 4, 5, 6, 7, 8)
20


In [9]:
def Squared(L):
    newList = [i**2 for i in L]
    return newList

L = input().split()
L = [int(i) for i in L]
print(Squared(L))


[1, 4, 9, 16]


# Python basics 03: Class of 27/02

In [27]:
! pip install numpy

## Importing Numpy

In [ ]:
import numpy
import numpy as np
from numpy import arange

## Create arrays
array elements have to be the same datatype

In [46]:
import numpy as np
list = [1,5,8,10,3]
print(list)

array = np.array(list)
print(array)

print(list * 2) #list is seen as whole, printed twice
print(array * 2) #array is seen element by element, each element is multiplied

list.append(2)
#array.append(2) Can't append --> fixed size!

#1D arrays
print(np.arange(10)) #evenly spaces intervals with given key, upperbound is out
print(np.zeros(10)) #10 0's --> x amount
print(np.ones(10)) #10 1's --> x amount

print(np.full(10,5)) #new arrays, certain length of specific element
print(np.random.randint(-5,6,10)) #new array, low included, high (not included), size
print(np.random.random(10)) #random array of floats of size x

[1, 5, 8, 10, 3]
[ 1  5  8 10  3]
[1, 5, 8, 10, 3, 1, 5, 8, 10, 3]
[ 2 10 16 20  6]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[-5  1  5 -2  4  4 -4  1 -1  0]
[0.2074096  0.49590484 0.51999191 0.69547919 0.65628796 0.43798753
 0.85087335 0.88872392 0.09766623 0.35133368]


## Reshaping & converting arrays

In [59]:
import numpy as np

#change array again
array = np.random.randint(-5,6,10)
print(array)
print(array.shape)
print(array.ndim)

print("array is of type:", array.dtype)
array_float = array.astype('f') #converts to specific datatype
# 'f' float / 'i' integer / 'b' boolean / 'M' datetime / 'S' string
print(array_float)

array_string = array.astype(str)
print(array_string)

#2D arrays
array_2D = np.reshape(array,(2,5))
print(array_2D)

array_2D = np.reshape(array,(5,2))
print(array_2D)

#needs to be a perfect fit
#array3D = np.reshape(array,(3,3))
#array_2D = np.reshape(array,(2,6))

[-5  0 -4 -5  0  3  4 -2 -4  5]
(10,)
1
array is of type: int32
[-5.  0. -4. -5.  0.  3.  4. -2. -4.  5.]
['-5' '0' '-4' '-5' '0' '3' '4' '-2' '-4' '5']
[[-5  0 -4 -5  0]
 [ 3  4 -2 -4  5]]
[[-5  0]
 [-4 -5]
 [ 0  3]
 [ 4 -2]
 [-4  5]]


## Slicing arrays
[start: end: step]

In [74]:
import numpy as np
array = np.array([6,8,2,9,3,1,4,7,0,5])
print(array)

print(array[1:5:1]) #[8 2 9 3]
print(array[1:5:]) #[8 2 9 3]
print(array[1:5:2]) #[8 9]

print(array[0:5:1]) #[6 8 2 9 3]
print(array[:5:1]) #[6 8 2 9 3] --> default start index = 0

print(array[0::1]) #[6 8 2 9 3 1 4 7 0 5]
print(array[0:10:1]) #[6 8 2 9 3 1 4 7 0 5]

#reverse array
print(array[::-1]) #[5 0 7 4 1 3 9 2 8 6]
print(array[0:10:-1]) #[] --> nothing in front of index 0
print(array[10::-1]) #[5 0 7 4 1 3 9 2 8 6]
print(array[10:0:-1]) #[5 0 7 4 1 3 9 2 8]

print(array[::2]) #[6 2 3 4 0]
print(array[::-2]) #[5 7 1 9 8]

[6 8 2 9 3 1 4 7 0 5]
[8 2 9 3]
[8 2 9 3]
[8 9]
[6 8 2 9 3]
[6 8 2 9 3]
[6 8 2 9 3 1 4 7 0 5]
[6 8 2 9 3 1 4 7 0 5]
[5 0 7 4 1 3 9 2 8 6]
[]
[5 0 7 4 1 3 9 2 8 6]
[5 0 7 4 1 3 9 2 8]
[6 2 3 4 0]
[5 7 1 9 8]


## Working with arrays

In [100]:
import numpy as np
a = np.arange(0,10) #[0 1 2 3 4 5 6 7 8 9]
b = np.arange(9,-1,-1) #[9 8 7 6 5 4 3 2 1 0]
print(a,b)

print(a+b)
print(a-b)
print(a*b)
#print(a/b) --> mind dividing by 0

print(np.where(a%2 == 0, a+1, a))
print(np.where(a%2 == 0, a, a+1))
# condition, x, y --> if condition is true execute first part, else second part

print(np.where(b>5)) #you get indexes back
print(np.where(b>5,b,0))

print()
b = np.reshape(b,(2,5))
print(b)
print()

print(b.sum(axis=0)) #sum of columns
print(b.min(axis=1)) #min value of rows
print(b.cumsum(axis=1)) #sum of all elements in rows

print()
print(a.sum())
print(a.min())
print(a.max())

print()
print(np.sqrt(a))
print(np.square(a))
print(np.sqrt(a.max()))



[0 1 2 3 4 5 6 7 8 9] [9 8 7 6 5 4 3 2 1 0]
[9 9 9 9 9 9 9 9 9 9]
[-9 -7 -5 -3 -1  1  3  5  7  9]
[ 0  8 14 18 20 20 18 14  8  0]
[1 1 3 3 5 5 7 7 9 9]
[ 0  2  2  4  4  6  6  8  8 10]
(array([0, 1, 2, 3], dtype=int64),)
[9 8 7 6 0 0 0 0 0 0]

[[9 8 7 6 5]
 [4 3 2 1 0]]

[13 11  9  7  5]
[5 0]
[[ 9 17 24 30 35]
 [ 4  7  9 10 10]]

45
0
9

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[ 0  1  4  9 16 25 36 49 64 81]
3.0


### Exercise: It's magic time
Read in a 1D array and a number of rows! Convert the array to 2D! Calculate the sum of each column and if all sums are equal --> you're dealing with a magic table.
<b>input</b><br>
2 7 0 8 4 1 1 0 10<br>
3<br>
<b>output</b><br>
True
<pre>
2   7   0
8   4   1
1   0   10
<i>11   11  11</i> --> MAGIC TABLE
</pre>

In [112]:
import numpy as np
s = input()
array1D = np.array(s.split())
array1D = array1D.astype('i')

rows = int(input())
array1D = np.reshape(array1D,(rows, len(array1D)//rows))
print(array1D)

sums = np.sum(array1D,axis=0) #0 is columns, 1 is rows
print(sums)

total = np.sum(sums)
if total // rows == sums[0]:
    print("MAGIC TABLE")
else:
    print("NO MAGIC HERE")

#other approach
check = True
for value in sums:
    if value != sums[0]:
        check = False
        break

if check is True:
    print("MAGIC TABLE")
else:
    print("NO MAGIC HERE")



[[ 2  7  0]
 [ 8  4  1]
 [ 1  0 10]]


TypeError: 'axis' is an invalid keyword argument for sum()